<page>
    <h1>Leave Group Call</h1>
    <text>This method allow leaving a Group Call.</text>
    <h3>Example</h3>
    <syntax-highlight mark="10-12">
        from pytgcalls import Client
        from pytgcalls import idle
        ...

        app = PyTgCalls(client)
        app.start()

        ...  # Call API methods

        app.leave_group_call(
            -1001185324811,
        )

        idle()
    </syntax-highlight>
    <separator/>
    <h2>Details</h2>
    <category-title>
        <ref>PyTgCalls.<sb>leave_group_call</sb></ref>()
    </category-title>
    <subtext>
        <text>Leave a group call</text>
        <br/>
        <category>
            <text><b>PARAMETERS</b></text>
            <subtext>
                <config id="ARG_CHAT_ID"/>
            </subtext>
        </category>
        <br/>
        <category>
            <text><b>RAISES</b></text>
            <subtext>
                <config id="BASE_EXCEPTIONS"/>

                <category-title>exception <ref>pytgcalls.exceptions.<sb>NotInGroupCallError</sb></ref></category-title>
                <subtext><text>This error occurs when attempting to leave a group call that you have not joined."</text></subtext>
            </subtext>
        </category>
    </subtext>
</page>